---
abstract: 'Generate a tree from a self-referential database table'
author:
  - 'Ron Savage <ron@savage.net.au>'
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-Tree
provides:
  DBIx::Tree:
    file: lib/DBIx/Tree.pm
    version: 1.91
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.91
